import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import ProductProvider, {
  ProductContext,
} from "@/components/ProductsContext/ProductsContext";
import Footer from "@/components/footer/Footer";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" w-3/4 m-auto">
          <ProductProvider>
            <Navbar />
            {children}
          </ProductProvider>
        </div>
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
